// <auto-generated />
using System;
using HomeworkMay13_BookmarkManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeworkMay13_BookmarkManager.Data.Migrations
{
    [DbContext(typeof(BookmarkManagerDataContext))]
    [Migration("20240515033345_Add TopBookmark DbSet")]
    partial class AddTopBookmarkDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeworkMay13_BookmarkManager.Data.Bookmark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("HomeworkMay13_BookmarkManager.Data.TopBookmark", b =>
                {
                    b.Property<int?>("BookmarkID")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasIndex("BookmarkID");

                    b.ToTable((string)null);

                    b.ToView("view_that_doesn't_exist", (string)null);
                });

            modelBuilder.Entity("HomeworkMay13_BookmarkManager.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeworkMay13_BookmarkManager.Data.TopBookmark", b =>
                {
                    b.HasOne("HomeworkMay13_BookmarkManager.Data.Bookmark", "Bookmark")
                        .WithMany()
                        .HasForeignKey("BookmarkID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bookmark");
                });
#pragma warning restore 612, 618
        }
    }
}
